name: Build

on:
  push:
    branches: [ refactor ]
  pull_request:
    branches: [ refactor ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt -y update && sudo apt-get install -y build-essential cmake libssl-dev libcurl4-gnutls-dev
    - name: configure
      run: cmake .
    - name: make
      run: make 
    - name: make check
      run: make check
    - name: test
      run: ./dist/unit-test
    