name: Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt -y update && sudo apt-get install -y build-essential cmake libssl-dev libcurl4-gnutls-dev
    - name: configure
      run: cmake .
    - name: make
      run: make 


  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt -y update && sudo apt-get install -y build-essential cmake libssl-dev libcurl4-gnutls-dev
    - name: Unit Tests
      run: make unit-test
    - name: test
      run: ./dist/unit-test